# Generated by Django 3.1.7 on 2021-04-15 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalmetrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomputer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gpumetrics',
            name='gpu_core',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpumetrics',
            name='gpu_hot_spot',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpumetrics',
            name='gpu_memory',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpumetrics',
            name='gpu_vrm_core',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='memorymetrics',
            name='available',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='memorymetrics',
            name='used',
            field=models.FloatField(),
        ),
    ]
