# Generated by Django 3.1.7 on 2021-04-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalmetrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpumetrics',
            name='gpu_core',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpumetrics',
            name='gpu_hot_spot',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpumetrics',
            name='gpu_memory',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpumetrics',
            name='gpu_vrm_core',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='memorymetrics',
            name='available',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='memorymetrics',
            name='used',
            field=models.FloatField(),
        ),
    ]
