# Generated by Django 3.1.7 on 2021-03-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPUMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_core', models.CharField(max_length=50)),
                ('gpu_memory', models.CharField(max_length=50)),
                ('gpu_vrm_core', models.CharField(max_length=50)),
                ('gpu_vrm_memory_1', models.CharField(max_length=50)),
                ('gpu_vrm_memory_2', models.CharField(max_length=50)),
                ('gpu_hot_spot', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
                ('hour_at', models.TimeField()),
            ],
            options={
                'verbose_name': 'metric',
                'verbose_name_plural': 'metrics',
            },
        ),
    ]
