# Generated by Django 3.1.7 on 2021-03-27 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpumetrics',
            name='gpu_vrm_memory_1',
        ),
        migrations.RemoveField(
            model_name='gpumetrics',
            name='gpu_vrm_memory_2',
        ),
        migrations.AddField(
            model_name='gpumetrics',
            name='pc',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='pc.personalcomputer'),
            preserve_default=False,
        ),
    ]
