# Generated by Django 3.1.7 on 2021-03-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpumetrics',
            name='gpu_vrm_memory_1',
        ),
        migrations.RemoveField(
            model_name='gpumetrics',
            name='gpu_vrm_memory_2',
        ),
    ]
