# Generated by Django 3.1.7 on 2021-03-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20210327_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpumetrics',
            options={'verbose_name': 'gpu_metric', 'verbose_name_plural': 'gpu_metrics'},
        ),
    ]
