# Generated by Django 3.1.7 on 2021-03-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
        ('metrics', '0005_auto_20210327_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.CharField(max_length=50)),
                ('available', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
                ('hour_at', models.TimeField()),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_temps', to='pc.personalcomputer')),
            ],
            options={
                'verbose_name': 'memory_metric',
                'verbose_name_plural': 'memory_metrics',
            },
        ),
    ]
