# Generated by Django 3.1.7 on 2021-03-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalComputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainboard', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=50)),
                ('processador', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'personal_computer',
                'verbose_name_plural': 'personal_computers',
            },
        ),
    ]
