# Generated by Django 3.1.7 on 2021-04-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0002_personalcomputer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcomputer',
            name='user',
        ),
    ]
